# [START django_app]
runtime: python38

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
# [END django_app]

env_variables:
    CLOUD_STORAGE_BUCKET: mcd_file_storage

instance_class:
  F4_1G
automatic_scaling:
  max_instances: 1 # you can adjust this as you wish)
  min_instances: 0 # will scale to 0 when there is no traffic so won't incur costs)