# Generated by Django 3.2.4 on 2021-06-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0004_alter_mcd_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcd_users',
            name='input_photos',
        ),
        migrations.RemoveField(
            model_name='mcd_users',
            name='output_photos',
        ),
        migrations.CreateModel(
            name='MCD_Photo_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_photo', models.CharField(max_length=150)),
                ('output_photo', models.CharField(blank=True, max_length=150, null=True)),
                ('uploaded_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcd.mcd_users')),
            ],
        ),
    ]
