# Generated by Django 3.2.4 on 2021-07-02 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcd', '0006_auto_20210626_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcd_photo_analysis',
            name='uploaded_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
