# Generated by Django 3.2.4 on 2021-07-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0008_mcd_photo_analysis_analysis_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcd_photo_analysis',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
