# Generated by Django 3.2.4 on 2021-07-04 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0010_mcd_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcd_photo_analysis',
            name='object_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mcd.mcd_object'),
        ),
    ]
