# Generated by Django 3.2.4 on 2021-07-05 11:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0011_mcd_photo_analysis_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcd_object',
            name='county',
            field=django_countries.fields.CountryField(default=None, max_length=746, multiple=True),
        ),
    ]
