# Generated by Django 3.2.4 on 2021-07-07 18:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0012_alter_mcd_object_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcd_photo_analysis',
            name='crack_length',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mcd_photo_analysis',
            name='date_analysed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mcd_photo_analysis',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mcd_object',
            name='county',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=746, multiple=True),
        ),
    ]
