# Generated by Django 3.2.4 on 2021-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0015_alter_mcd_photo_analysis_record_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcd_object',
            old_name='num_photos',
            new_name='num_records',
        ),
        migrations.RenameField(
            model_name='mcd_photo_analysis',
            old_name='date_analysed',
            new_name='datetime_analysed',
        ),
        migrations.RenameField(
            model_name='mcd_photo_analysis',
            old_name='date_taken',
            new_name='datetime_taken',
        ),
        migrations.AddField(
            model_name='mcd_photo_analysis',
            name='datetime_uploaded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mcd_record',
            name='num_images',
            field=models.IntegerField(default=0),
        ),
    ]
