# Generated by Django 3.2.4 on 2021-07-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0017_mcd_object_num_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcd_photo_analysis',
            name='scale',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, null=True),
        ),
    ]
