# Generated by Django 3.2.4 on 2021-07-12 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcd', '0018_mcd_photo_analysis_scale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MCD_Object',
            new_name='MCD_Project',
        ),
    ]
