# Generated by Django 3.2.4 on 2021-07-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0019_rename_mcd_object_mcd_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcd_photo_analysis',
            old_name='object_id',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='mcd_record',
            old_name='object_id',
            new_name='project_id',
        ),
    ]
