# Generated by Django 3.2.4 on 2021-07-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0020_auto_20210712_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcd_photo_analysis',
            name='overlay_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
