# Generated by Django 3.2.4 on 2021-07-08 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcd', '0013_auto_20210707_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCD_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Record', max_length=100)),
                ('object_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mcd.mcd_object')),
                ('uploaded_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mcd_photo_analysis',
            name='record_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mcd.mcd_record'),
        ),
    ]
