# Generated by Django 3.2.4 on 2021-07-08 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0014_auto_20210708_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcd_photo_analysis',
            name='record_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcd.mcd_record'),
        ),
    ]
