# Generated by Django 3.2.4 on 2021-06-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0002_rename_users_mcd_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcd_users',
            name='input_photos',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mcd_users',
            name='output_photos',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mcd_users',
            name='password',
            field=models.CharField(default='default', max_length=60),
            preserve_default=False,
        ),
    ]
