# Generated by Django 3.2.4 on 2021-07-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcd', '0007_alter_mcd_photo_analysis_uploaded_by_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcd_photo_analysis',
            name='analysis_complete',
            field=models.BooleanField(default=False),
        ),
    ]
